// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApCpJHrEoIi6N-a0f7sFb3o2bcOBjnyU0',
    appId: '1:691542539827:web:29928ad455cfe9fc05ad46',
    messagingSenderId: '691542539827',
    projectId: 'securguinee',
    authDomain: 'securguinee.firebaseapp.com',
    storageBucket: 'securguinee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsQiuVxpoUPzKqaIiQ0AnDGQWCPpNS-pM',
    appId: '1:691542539827:android:1562cd23be6de13b05ad46',
    messagingSenderId: '691542539827',
    projectId: 'securguinee',
    storageBucket: 'securguinee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPHI1IaK_toKPVWZIPo0-j6VbP_H7iOQc',
    appId: '1:691542539827:ios:088abe38a55b657705ad46',
    messagingSenderId: '691542539827',
    projectId: 'securguinee',
    storageBucket: 'securguinee.firebasestorage.app',
    iosBundleId: 'com.example.securdiawara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPHI1IaK_toKPVWZIPo0-j6VbP_H7iOQc',
    appId: '1:691542539827:ios:088abe38a55b657705ad46',
    messagingSenderId: '691542539827',
    projectId: 'securguinee',
    storageBucket: 'securguinee.firebasestorage.app',
    iosBundleId: 'com.example.securdiawara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApCpJHrEoIi6N-a0f7sFb3o2bcOBjnyU0',
    appId: '1:691542539827:web:b0cefe0d497cf80205ad46',
    messagingSenderId: '691542539827',
    projectId: 'securguinee',
    authDomain: 'securguinee.firebaseapp.com',
    storageBucket: 'securguinee.firebasestorage.app',
  );
}
